"use client";
import { useRef, useState } from "react";
const API = process.env.NEXT_PUBLIC_API_URL || "http://127.0.0.1:8000";
export default function Upload({ onUploaded }: { onUploaded: () => void }) {
  const input = useRef<HTMLInputElement>(null); const [file, setFile] = useState<File | null>(null); const [uploaderName, setUploaderName] = useState(""); const [busy, setBusy] = useState(false); const [error, setError] = useState("");
  async function upload() { if (!file) { setError("Select an Excel file to continue."); return; } if (!uploaderName.trim()) { setError("Enter your name before uploading."); return; } setBusy(true); setError(""); try { const body = new FormData(); body.append("file", file); body.append("uploader_name", uploaderName.trim()); if (!/\d{2}[.\-_]\d{2}[.\-_]\d{4}/.test(file.name)) { const date = window.prompt("Enter reporting date as YYYY-MM-DD:"); if (!date) throw new Error("A reporting date is required."); body.append("reporting_date", date); } const response = await fetch(`${API}/api/upload`, { method: "POST", body }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.detail || "The file could not be read."); onUploaded(); } catch (cause) { setError(cause instanceof Error ? cause.message : "Upload failed."); } finally { setBusy(false); } }
  return <main className="waste-shell grid min-h-screen place-items-center px-5 py-10 text-slate-900"><section className="w-full max-w-xl rounded-3xl border border-slate-200 bg-white shadow-2xl"><div className="bg-slate-950 px-7 py-8 text-white"><div className="grid h-11 w-11 place-items-center rounded-xl bg-teal-400 text-lg font-black text-slate-950">M</div><p className="mt-6 text-[10px] font-bold uppercase tracking-[.22em] text-teal-300">CPP operations control</p><h1 className="mt-2 text-2xl font-bold">Start with your Waste report</h1><p className="mt-2 text-sm text-slate-300">Upload an Excel workbook to create the Waste dashboard.</p></div><div className="p-7"><label className="block text-sm font-semibold text-slate-700">Your name<input value={uploaderName} onChange={e => { const value = e.target.value; setUploaderName(value); if (value.trim()) setError(""); }} placeholder="Enter your name" className="mt-1.5 w-full rounded-xl border border-slate-200 px-3 py-2.5 font-normal" /></label><button type="button" onClick={() => input.current?.click()} className="mt-5 flex w-full flex-col items-center rounded-2xl border-2 border-dashed border-teal-200 bg-teal-50 px-6 py-9"><strong className="text-sm">{file ? file.name : "Choose an Excel file"}</strong><span className="mt-1 text-xs text-slate-500">Supported: .xls, .xlsx, .xlsb</span></button><input ref={input} type="file" accept=".xls,.xlsx,.xlsb" className="hidden" onChange={e => { setFile(e.target.files?.[0] || null); setError(""); }} />{error && !uploaderName.trim() && <p className="mt-4 rounded-xl bg-rose-50 px-3 py-2 text-sm text-rose-700">{error}</p>}<button onClick={upload} disabled={!file || busy} className="mt-5 w-full rounded-xl bg-teal-700 px-4 py-3 text-sm font-bold text-white disabled:bg-slate-300">{busy ? "Reading Waste sheet..." : "Upload and open dashboard"}</button></div></section></main>;
}

